### ISSUE TITLE
BUG: Badly packaged library

### ISSUE THREAD

**Issue by servrox** [mediamanDE/angular-mm-responsive-image#10]
Angular CLI: 6.0.8
Node: 10.4.1
OS: win32 x64
Angular: 6.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3

**> Issue description:**

When using the MmResponsiveImageComponent like described, 
following error is preventing the project from compiling properly:

`ERROR in ./node_modules/mm-responsive-image/src/app/mm-responsive-image.component.ts
Module build failed: Error: C:\dev\deleteMe\node_modules\mm-responsive-image\src\app\mm-responsive-image.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\dev\deleteMe\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:709:23)
    at plugin.done.then (C:\dev\deleteMe\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

When adding the the module to _tsconfig.app.json_ 

`{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts",
    "../node_modules/mm-responsive-image/**/*.spec.ts"
  ],
  "include": [
    "**/*.ts",
    "../node_modules/mm-responsive-image/**/*.ts"
  ]
}
`

and to _tsconfig.spec.json_ 

`{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "module": "commonjs",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "test.ts",
    "polyfills.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts",
    "../node_modules/mm-responsive-image/**/*.spec.ts",
    "../node_modules/mm-responsive-image/**/*.d.ts"
  ]
}
`

Following error appears:

`ERROR in node_modules/mm-responsive-image/src/main.ts(3,10): error TS2305: Module '"C:/dev/deleteMe/node_modules/mm-responsive-image/src/app/index"' has no exported member 'MmResponsiveImage'.`

**> Expected behavior:**

To work with Angular 6.

**Comment by R4c00n** [comment]
Hallo @Servrox,
yes you're right. Right now this library only works with Angular 4.x.
I will see if I can find the time to update the dependencies so that it works with Angular >= 6.
You can also try to do this on your own and contribute a Pull Request :)

**Comment by R4c00n** [comment]
Hello @Servrox,
the issue should be fixed in version 2.0.0. Please reopen this issue if it's still not working for you.
